version: '3'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/pi/monitoring/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  influxdb:
    image: arm64v8/influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /home/pi/monitoring/influxdb/data:/var/lib/influxdb
      - /home/pi/monitoring/influxdb/config:/etc/influxdb2
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_DB=grafana
     # - INFLUXDB_INIT_MODE=setup
     # - INFLUXDB_INIT_ORG=ORGNAME
     # - INFLUXDB_INIT_BUCKET=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
     # - INFLUXDB_INIT_USERNAME=grafana
     # - INFLUXDB_INIT_PASSWORD=grafana
     #- DOCKER_INFLUXDB_INIT_MODE=setup
     #- DOCKER_INFLUXDB_INIT_USERNAME=admin
     #- DOCKER_INFLUXDB_INIT_PASSWORD=admin123
     #- DOCKER_INFLUXDB_INIT_ORG=ORGNAME
     #- DOCKER_INFLUXDB_INIT_BUCKET=bucket
     #- DOCKER_INFLUXDB_HTTP_AUTH_ENABLED=true
    restart: unless-stopped

  pi_exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pi_exporter
    environment:
      - PIHOLE_HOSTNAME=192.168.1.5
      - PIHOLE_PASSWORD=PASSWORD
      - INTERNAL=30s
      - PORT=9617
    ports:
      - "9617:9617"
    restart: unless-stopped

#  plexcollector:
#    image: plexcollector
#    container_name: plexcollector
#    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor-arm64:v0.45.0
    container_name: cadvisor
    # ports:
    #  - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
